### PR TITLE
Add new packgaes meta field

### LINKED ISSUE #1013: Allow user-defined tags from external packages, have a way to load an external package in `roxygenize()`
Before:

```yaml
Roxygen: { library(roxygenlabs); list(markdown = TRUE,
    roclets = c("collate", "namespace", "roxygenlabs_rd")) }
```

After:

```yaml
Roxygen: list(
      markdown = TRUE,
      roclets = c("collate", "namespace", "roxygenlabs::roxygenlabs_rd")
    )
```

### PR DESCRIPTION
**Pull request by hadley**
Not sure how to test this, but hopefully it's sufficiently simple I didn't mess it up.

Fixes #1013

### CODE REVIEW

**Comment by hadley** [comment]
@gaborcsardi `requireNamespace()` already errors if the package isn't found?

**Comment by gaborcsardi** [comment]
> @gaborcsardi requireNamespace() already errors if the package isn't found?

@hadley But you call it with `quietly = TRUE`, in which case it does not error:
https://github.com/r-lib/roxygen2/pull/1059/files#diff-5536902b32f437aa37fb6527dece2f7cR45

```r
❯ requireNamespace("foobarsdfsdf", quietly = TRUE)
❯
```

Actually, even with `quietly = FALSE` it does not error, just prints an error message:

```r
❯ { requireNamespace("foobarsdfsdf", quietly = FALSE); print("still here") }
Loading required namespace: foobarsdfsdf
Failed with error:  ‘there is no package called ‘foobarsdfsdf’’
[1] "still here"
```

**Comment by gaborcsardi** [comment]
On the bright side, I tried it on a package, and it does work nicely.

**Comment by hadley** [comment]
Oh, maybe I should by using `loadNamespace()`?

**Comment by gaborcsardi** [comment]
Yeah, that's good as well, that will error for sure.

**Pull request merged**
