### PR TITLE
Add a clickable link to file when already exists and not generated by roxygen2

### PR DESCRIPTION
**Pull request by olivroy**
An alternative would also be to use 

```r
"Skipping {.path {path}}"
```

Using the approach in the [cli manual]( https://cli.r-lib.org/reference/links.html?q=file#link-text-1)

image

I removed the snapshot test and test for FALSE manually.

### CODE REVIEW

**Comment by hadley** [comment]
Why remove the snapshot test?

**Comment by olivroy** [comment]
It had a stochastic output. I could use `transform` to restore it, but I didn't know about it then!

**Comment by hadley** [comment]
Oooh because it's a temp file.

**Comment by olivroy** [comment]
I restored the snapshot test and fixed a bracket typo! This is ready for your review

**Comment by hadley** [comment]
Perfect, thank you!

**Pull request merged**
