### PR TITLE
R6 class support

### LINKED ISSUE #388: Documentation for R6 methods
Should look something like this:

---
# Methods
## Method 1

```
class$method(a, b, c = 12)
```

Description.
### Parameters
- Param 1
- Param 2
- Param 3
### Returns

What the method returns
### Example

``` R
a <- 10
b <- 5
a + b
#> [1]
```

---

Rd would look something like:

``` latex
\section{Methods}{
\subsection{\code{method1}}{

\code{class$method1(a, b, c = 12}

\subsection{Parameter}{

}
}
```

and similarly for fields. 

Parameters, returns, and methods would be optional. If no methods use them, just list usage + (optional) description with bullets.  Can also use top-level `@examples` if you want to put all examples in one place.

### PR DESCRIPTION
**Pull request by gaborcsardi**
> This is far from being ready, I am opening it for discussion. Feedback is welcome.

Still coming:
- [x] consistent naming of the `initialize()` / `new()` method
- [x] support for fields, right now they have to be documented manually, via `@field`.
- [x] support for active bindings, they are manual for now, via `@field` as well.
- [x] add inheritance information, i.e. link to superclasses
- [x] ~get rid of the compulsory `@details` tag, in the main part and also before a method~ (maybe later)
- [x] support `@description` as well
- [x] change method docs order: 1. Description 2. Usage 3. Arguments 4. Details.
- [x] check that all public methods are documented
- [x] check that docs and `names(formals())` of method arguments match
- [x] ~allow `inheritParams()` from methods~ (maybe later)
- [x] ~allow `inheritSection()` from methods, maybe~ (maybe later)
- [x] ~allow `@inheritDotParams()` from methods~ (maybe later)
- [x] allow documenting a common argument up front in the class, and then automatically use this in the documentation of the methods
- [x] ~A test(that) helper to run the code in the examples, because these do not
      run in `R CMD check`.~
- [x] Dump all the methods examples into a big `\examples{}` block at the end, so 
      they are tested.
- [x] ~~should we used `\describe{}` for the list of arguments? Probably....~~
- [x] actually arguments are in a table, so we should do that instead...
- [x] ~support methods added via `set()`.~ (maybe layer)
- [x] ~support user defined `clone()` methods.~ (maybe later)
- [x] ~support documenting private methods, fields, active bindings?~ (maybe later)
- [x] test cases
- [x] documentation
- [x] ~a vignette?~ (maybe later)
- [x] check what CSS or other updates pkgdown needs to format the reference pages well.
- [x] Fix paragraphs in argument blocks, because they are not wrapped currently. 
- [x] Format warnings the usual roxygen way.

This is the current syntax:

```r
#' R6 class for a person
#' 
#' Description of the class.
#' 
#' @details
#' Details of the class.
#' 
#' @section Public fields:
#' * `name`: first name.
#' * `hair`: hair color.

Person <- R6Class("Person",
  public = list(
    name = NULL,
    hair = NULL,

    #' @details
    #' Create a new `Person` object.
    #' 
    #' @param name First name.
    #' @param hair Hair color, if known.
    #' @return A person object.
    #' 
    #' @examples
    #' Person$new("Ann", "black")

    initialize = function(name = NA, hair = NA) {
      self$name <- name
      self$hair <- hair
      self$greet()
    },

    #' @details
    #' Set new hair color.
    #' 
    #' @param val The new hair color.
    #' @return The new color, invisibly.
    #' 
    #' @examples
    #' ann <- Person$new("Ann", "black")
    #' ann$hair
    #' ann$set_hair("red")
    #' ann$hair

    set_hair = function(val) {
      self$hair <- val
    },

    #' @details
    #' Make the person greet.
    #' 
    #' @examples
    #' ann <- Person$new("Ann", "black")
    #' ann$greet()

    greet = function() {
      cat(paste0("Hello, my name is ", self$name, ".\n"))
    }
  )
)
```

This will generate the following:
```
Person               package:pkgdepends                R Documentation

R6 class for a person

Description:

     Description of the class.

Details:

     Details of the class.

Public fields:

        • ‘name’: first name.

        • ‘hair’: hair color.

Methods:

  Public methods:

         • ‘Person$new()’

         • ‘Person$set_hair()’

         • ‘Person$greet()’

  Method 'new()':

       Person$new(name = NA, hair = NA)

     Create a new ‘Person’ object.

    Arguments:

           • ‘name’: First name.

           • ‘hair’: Hair color, if known.


    Returns:

         A person object.


    Examples:

         Person$new("Ann", "black")


  Method 'set_hair()':

       Person$set_hair(val)

     Set new hair color.

    Arguments:

           • ‘val’: The new hair color.


    Returns:

         The new color, invisibly.


    Examples:

         ann <- Person$new("Ann", "black")
         ann$hair
         ann$set_hair("red")
         ann$hair


  Method 'greet()':

       Person$greet()

     Make the person greet.

    Examples:

         ann <- Person$new("Ann", "black")
         ann$greet()
```

This is how it looks in RStudio:

Screen Shot 2019-09-26 at 10 36 57 AM

It _could_ look, nicer, e.g. with some extra CSS:

Screen Shot 2019-09-26 at 10 38 09 AM

Closes #388.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Apart from the "usual" `@inheritParams`, it seems like it would be useful to be able to document the same parameter for several methods up front. I'll add this to the list.

**Comment by sckott** [comment]
What about examples?  Seems like maybe `\examples` in man files is needed so that cmd check & `devtools::run_examples` will run examples? Maybe `devtools::run_examples` could find and run the `\subsection{Examples}{...}`  sections created by the doc sections in R6 public methods?

**Comment by gaborcsardi** [comment]
@sckott You can have `@examples` in the main block, e.g. to showcase all/most of the methods, and that'll be `\examples{}` in the man page, and CRAN will be happy as well.

**Comment by sckott** [comment]
right, that's what I currently do. Should best practice be then to not have examples in public method blocks since they could not be working examples?

**Comment by gaborcsardi** [comment]
> Should best practice be then to not have examples in public method blocks since they could not be working examples?

IDK, I think I want to have examples for the methods sometimes, and then have a helper among the test cases to make sure that they run.

You still cannot run them with `example()`, but that seems tricky to fix.

**Comment by gaborcsardi** [comment]
@sckott Now we also dump all the method examples into a large `\examples{}` block at the end, so it is tested by `R CMD check` and no helpers etc. are needed.

**Comment by gaborcsardi** [comment]
@hadley All TODO list items are done.

**Comment by hadley** [comment]
Thanks @gaborcsardi!!

**Comment by wch** [comment]
Awesome!

**Pull request merged**
