### PR TITLE
Support Markdown in custom `@family` titles

### PR DESCRIPTION
**Pull request by salim-b**
Parses [custom `@family` titles](https://roxygen2.r-lib.org/articles/index-crossref.html) as Markdown.

### CODE REVIEW

**Comment by hadley** [comment]
Do the family name also end up in the concept tag?

**Comment by salim-b** [comment]
> Do the family name also end up in the concept tag?

Sorry, I don't understand the question... what are you exactly referring to with "the concept tag"?

AFAICT, the `tag` arg given to `markdown()` is only used to create better error and warning msgs...

**Comment by hadley** [comment]
I think family names also end up in `\concept{}`

**Comment by salim-b** [comment]
> I think family names also end up in `\concept{}`

Yes, the family *name*, not the value (for which this PR adds Markdown support).

**Comment by hadley** [comment]
Ah great.

**Pull request merged**
