### PR TITLE
Prefer markdown throughout the vignette

### PR DESCRIPTION
**Pull request by michaelquinn32**
This is more in line with the tidyverse style guide.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Good idea! I am not sure about the `\describe{},` though, because the markdown is not really equivalent.

**Comment by michaelquinn32** [comment]
Thanks for the feedback!

Maybe others might be interested in chiming in, but I believe:

* Having one way of doing things, especially if it follows the style guide, is always better
* It doesn't really matter that the markdown to Rd conversion matches describe; it's close enough
* The markdown version is more readable anyway, diminishing the importance of the output further

I would imagine that the last part is a bit contentious. Is the true target for the documentation the code itself or another format (like what we call from interactive R)? At Google, we mostly care about the inline documentation, and the generated Rd files are of secondary importance. I would be happy to sacrifice `\describe{}` if I can get a close-enough markdown equivalent.

**Comment by gaborcsardi** [comment]
Yeah, I don't have any hard data, but strongly suspect that most R users do not read the docs from the code of the package, but either via the (HTML) help browser, or the (different HTML) pkgdown web site.

**Comment by michaelquinn32** [comment]
Here's a use of `describe`:
https://rdrr.io/cran/psych/man/Gleser.html

This is pretty close to a markdown list without bullets. If I add formatting to those items, would that be close enough?

**Comment by gaborcsardi** [comment]
This is in the terminal, first the markdown list, then the `\describe{}`:

```
        • ‘foo’: Often status messages are associated with processes.
          E.g. the app starts downloading a large file, so it sets the
          status bar accordingly. Once the

        • ‘bar’: short one

        • another one: Often status messages are associated with
          processes. E.g. the app starts downloading a large file, so
          it sets the status bar accordingly. Once the

     ‘foo’: Often status messages are associated with processes. E.g.
          the app starts downloading a large file, so it sets the
          status bar accordingly. Once the

     ‘bar’: short one

     ‘another one’: Often status messages are associated with
          processes. E.g. the app starts downloading a large file, so
          it sets the status bar accordingly. Once the
```

And this is in the HTML help, in RStudio:

Screen Shot 2020-02-26 at 00 35 25

The `\describe{}` output is better, I think. So I am not sure if we should change this in the manual just yet. Ideally, we would have a way to write a description list in commonmark markdown.

**Comment by michaelquinn32** [comment]
Fair enough. I can revert that change so the section stuff can be checked in.

**Comment by hadley** [comment]
Thanks @michaelquinn32 !

**Pull request merged**
