### PR TITLE
FIX @exportS3method -> @exportS3Method

### PR DESCRIPTION
**Pull request by HenrikBengtsson**

### CODE REVIEW

**Comment by hadley** [comment]
Can you motivate this change for me? (Apologies if you already have but I've forgotten)

**Comment by olivroy** [comment]
@hadley The tag name is `@exportS3Method`, but some interactive advice mentions the non-existing `@exportS3method` tag. This PR would fix #1585, #1591

**Comment by hadley** [comment]
Ah got it, thanks!

**Comment by MichaelChirico** [comment]
+1 just hit this to. I copy-pasted the `exportS3method` in the error and was all the more confused when the error became "unknown tag".

Maybe it makes sense to add `exportS3method` as an alias as well? capitalization doesn't seem all that important here...

**Pull request merged**
