### PR TITLE
Add support for tags @cite and @bibliography

### PR DESCRIPTION
**Pull request by renozao**
Hi,

these commits add support for tags @cite and @bibliography so that references to papers can be added in Rd files by referencing bibtex entries with tag @cite.
All entries are gathered in the file int/REFERENCES.bib in the package directory.
Computations is cached for speed, and warnings are thrown when bibtex entries were not found in any of the declared bibliography files, at process time of the rd_roclet.
The file int/REFERENCES.bib gets updated when new @cite references are added in roxygen chunks.
NB: Bibtex entries not referenced in roxygen chunks are not automatically removed from the REFERENCES.bib file, since those may be used in the package's vignettes.

So users can do the following:

1- declare its bibtex database file in any roxygen chunk (e.g. in the chunk that describes the package): 

``` R
#' @docType package
#' @bibliography /home/user/articles.bib
NULL
```

The file `/home/user/articles.bib` must contain bibtex references (e.g. `@article{Ref2010, author=Somebody, year=2010, title={{A nice paper to read}}, journal={Good Journal}, ...}`.
Multiple bibliography files are supported, using multiple @bibliography tags.
The file inst/REFERENCES.bib is loaded by default so one does not need to add a @bibliography tag for it.

2- then reference papers in any other chunk using the bibtex keys, multiple references are supported using multiple @cite tags or comma or space-separated keys.
I also added support for a command `\cite`, which acts as the Latex command `\cite`, and is substituted by a short reference in the text and adds a full reference in the _References_ section:

``` R
#' Some function
#'
#' This function implements the method from \cite{Toto2010}.
#' An interesting book is \cite{Darwin1859}.
#'
#' @cite Otherref 
#' 
myfun <- function(...){
# ...
# ...
}
```

This will generated an Rd file with section references looking like the following:

``` Rd
\title{Some function}
\description{
This function implements the method from \cite{Toto et al. (2010)}.
An interesting book is \cite{Darwin (1859)}.
}
\references{
Toto et al. (2010). 
"A nice paper to read"
Good Journal

Charles Darwin (1859). 
"On the Origin of Species"

% output of Otherref
}
```

The man page for bibliography_roclet() contains more details on the new feature:

``` R
library(devtools)
dir.create('libcite')
.libPaths(c('libcite', .libPaths()))
install_github('roxygen', 'renozao', 'cite')
library(roxygen2)
?bibliography_roclet
```

Hope people you will find it as useful and easy to use.

### CODE REVIEW

**Comment by fgnu** [comment]
Hi Hadley, any chance that this pull request can be reviewed? Is there similar functionality elsewhere in the package?

**Comment by NattyE** [comment]
I agree it would be nice to have this functionality in roxygen2.

**Comment by coatless** [comment]
@hadley: Could this be reviewed again especially since the ability to support markdown tags was recently added?

**Comment by lrnv** [comment]
Hi @hadley 

Small Bump. Is Roxygen2 still in maintenance mode ? Can this old code still be merged ?

**Comment by GreatEmerald** [comment]
If roxygen2 is in maintenance mode, then what is its successor?

**Pull request closed without merging**
