### PR TITLE
Tweak tests

### PR DESCRIPTION
**Pull request by krlmlr**
- Close connections
- Test for reference to function call

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Wow, I didn't even know that you could do this. :) Maybe we should document it better. LGTM.

**Comment by krlmlr** [comment]
Yeah, that other test was wishful thinking :upside_down_face:. Do we want this?

**Comment by gaborcsardi** [comment]
Oh, a pity. Do we want to make it work?

**Comment by krlmlr** [comment]
Sure, in case you stumble over the code that handles this. I might do it too.

**Comment by hadley** [comment]
When I run the tests locally I still see:

```
Warning messages:
1: In for (i in seq_len(n)) { :
  closing unused connection 7 (/tmp/Rtmp7Ipg2M/file100e22c2f4a4a)
2: In for (i in seq_len(n)) { :
  closing unused connection 6 (/tmp/Rtmp7Ipg2M/file100e2201e67c7)
```

**Comment by maxheld83** [comment]
I think I've now got all unbalanced connections covered in #1192, including the above remaining.

**Comment by hadley** [comment]
Closing since the main part seems to have been done in #1192.

**Pull request closed without merging**
